[tool.poetry]
name = "test-project"
version = "0.1.0"
description = "A test project for Python LSP integration tests"
authors = ["Test <test@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"