name: Go Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true

      - name: Install gopls
        run: go install golang.org/x/tools/gopls@latest

      - name: Build
        run: go build -o mcp-language-server

      - name: Run tests
        run: go test ./...

      - name: Run code quality checks
        run: |
          # Install just if needed
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

          # Run code quality checks via justfile
          just check
