name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests and Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true

      - name: Build
        run: go build -o mcp-language-server

      - name: Install just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Install gopls
        run: go install golang.org/x/tools/gopls@latest

      - name: Run unit tests
        run: go test ./internal/...

      - name: Run code quality checks
        run: just check

  go-integration-tests:
    name: Go Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true

      - name: Install gopls
        run: go install golang.org/x/tools/gopls@latest

      - name: Run Go integration tests
        run: go test ./integrationtests/languages/go/...

  python-integration-tests:
    name: Python Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pyright
        run: npm install -g pyright

      - name: Run Python integration tests
        run: go test ./integrationtests/languages/python/...

